unit Model.CupomFiscalItem;

interface

function GetCupomFiscalItem : String;

implementation

uses
  System.Classes;

function GetCupomFiscalItem : String;
var
  FSQL : TStringList;
begin
  FSQL := TStringList.Create;
  try
    FSQL.Clear;
    FSQL.Add('select ID, ITEM, ID_PRODUTO, QTD, PERC_ICMS, ');
    FSQL.Add('VLR_UNITARIO, PERC_DESCONTO, VLR_DESCONTO, BASE_ICMS, ');
    FSQL.Add('VLR_ICMS, VLR_TOTAL, ID_CFOP, UNIDADE, CANCELADO, ');
    FSQL.Add('SITTRIB, TAMANHO, REFERENCIA, PERC_TRIBUTO, VLR_TRIBUTO, ');
    FSQL.Add('ID_NCM, ORIGEM_PROD, PERC_TRIBUTO_ESTADUAL, ');
    FSQL.Add('PERC_TRIBUTO_MUNICIPAL, PERC_TRIBUTO_FEDERAL, FONTE_TRIBUTO, ');
    FSQL.Add('VERSAO_TRIBUTO, VLR_TRIBUTO_FEDERAL, VLR_TRIBUTO_ESTADUAL, ');
    FSQL.Add('VLR_TRIBUTO_MUNICIPAL, ID_CSTICMS, ID_CSTIPI, ID_COFINS, ');
    FSQL.Add('ID_PIS, PERC_TRIBICMS, ID_VARIACAO, PERC_PIS, PERC_COFINS, ');
    FSQL.Add('PERC_IPI, TIPO_PIS, TIPO_COFINS, VLR_PIS, VLR_COFINS, VLR_IPI, ');
    FSQL.Add('VLR_DESCONTORATEIO, NOME_PRODUTO, ITEM_ORIGINAL, ID_PEDIDO, ');
    FSQL.Add('ITEM_PEDIDO, NUM_PEDIDO, ITEM_CLIENTE, NUMERO_OC, NUMERO_OS, ');
    FSQL.Add('ID_ENQIPI, QTD_DEVOLVIDA, ID_COR_COMBINACO, VLR_ACRESCIMO, ');
    FSQL.Add('VLR_UNIT_ORIGINAL, BASE_ICMSSUBST_RET, VLR_ICMSSUBST_RET, ');
    FSQL.Add('VLR_BASE_EFET, VLR_ICMS_EFE, PERC_ST, PERC_ICMS_EFET, ');
    FSQL.Add('PERC_BASE_RED_EFET, VLR_JUROS, VLR_ICMS_SUBSTITUTO, COD_CBENEF, ');
    FSQL.Add('QTD_TROCA, OBSERVACAO, ID_COMANDA, ITEM_COMANDA, STATUS, ');
    FSQL.Add('DATA_HORA_PEDIDO, ITEM_PRINCIPAL, VALOR_RATEIO_RECIBO, ');
    FSQL.Add('VALOR_RATEIO_TROCA, VALOR_RATEIO_RECIBO_TROCA, PRECO_CUSTO, ');
    FSQL.Add('VALOR_RATEIO_VALE, VALOR_RATEIO_CASH, ID_BARRIL, ID_ITEM, ');
    FSQL.Add('PRECO_CUSTO_TOTAL, ID_NOTA, ALIQ_ICMS_ADREM, VLR_ICMS_MONO, ');
    FSQL.Add('COM_GELO, COM_LIMAO, QTD_COPOS, ID_ORIGINAL, ID_TERMINAL ');
    FSQL.Add('from CUPOMFISCAL_ITENS ');
    FSQL.Add('WHERE 0 = 0 ');
    Result := FSQL.Text;
  finally
    FSQL.Free;
  end;
end;

end.
